M48
; DRILL file {KiCad (6.0.9)} date Fri Feb  3 11:30:57 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-03T11:30:57+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.520
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X95.5Y-61.0
X95.5Y-68.5
T2
X82.7Y-86.1
X101.7Y-112.6
X122.4Y-105.8
X139.4Y-122.8
X156.4Y-105.8
X177.5Y-42.3
X177.8Y-70.3
T0
M30
