M48
; DRILL file {KiCad (6.0.9)} date Thu Feb  2 11:22:58 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-02T11:22:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.520
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X193.75Y-87.1
X193.75Y-94.6
T2
X133.8Y-107.9
X152.8Y-134.4
X169.293Y-118.193
X197.293Y-117.893
T0
M30
